image: test_map.png
mode: trinary
resolution: 0.05 # 1 pixel = 5 cm
origin: [-10.0, -10.0, 0.0]  # La position (x,y,z) du pixel en bas Ã  gauche dans le monde
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196